autovc:
  rec_weight: 1
  pst_weight: 1
  cnt_weight: 1
  config:
    content_encoder:
    prenet:
    decoder:
    postnet:
embed:
  embed_dim: 80
train:
  batch_size: 2
  num_workers: 0
  lr: 0.0001
  lr_step: 8
  lr_gamma: 0.1
  epochs: 40